_target_: pytorch_lightning.Trainer

accelerator: gpu
strategy:
  _target_: pytorch_lightning.plugins.training_type.ddp.DDPPlugin
  find_unused_parameters: true # Needed for GAN training
gpus: ${gpus}
precision: 32
max_steps: 100000
# val_check_interval: 10000 # Lightning does not permit check intervals longer than 1 epoch
check_val_every_n_epoch: ${check_val_every_n_epoch}
replace_sampler_ddp: false
benchmark: true
