model_checkpoint:
  _target_: callbacks.default.CustomModelCheckpoint
  filename: "{epoch:03d}-{step:07d}"
  every_n_train_steps: 1000
  save_top_k: -1
  save_last: true
  dirpath: checkpoints
  auto_insert_metric_name: false
  verbose: true

wandb:
  _target_: callbacks.wandb_cb.WandBCallback
