_target_: datamodule.sr_datamodule.SRDataModule
train_dataset:
  _target_: dataset.sr_dataset.BlindSRDataset
  hq_data_dir: ${train_hq_data_dir}
  sr_scale: ${sr_scale}
  n_channels: 3
  degradation_type: ${degradation_type}
  is_training: True
  shuffle_prob: 0.1
  use_sharp: False
  hq_patch_size: null
  lq_patch_size: 256
val_dataset:
  _target_: dataset.sr_dataset.BlindSRDataset
  hq_data_dir: ${val_data_dir}
  sr_scale: ${sr_scale}
  n_channels: 3
  degradation_type: ${degradation_type}
  is_training: False
  shuffle_prob: 0.1
  use_sharp: False
  hq_patch_size: null
  lq_patch_size: 256
batch_size: ${batch_size}
num_workers: ${num_workers}
num_val_workers: 16
iterations_per_epoch: ${iterations_per_epoch}
use_random_sampler: True
